# Generated by Django 5.0.1 on 2025-05-21 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('call_sign', models.CharField(choices=[('DRK', 'DRK'), ('BTN', 'BTN')], max_length=10)),
                ('aircraft_type', models.CharField(choices=[('ATR42', 'ATR42'), ('A319', 'A319'), ('A320neo', 'A320neo')], max_length=20)),
                ('runway', models.CharField(choices=[('15', '15'), ('33', '33')], max_length=3)),
                ('occurrence', models.CharField(choices=[('Go Around', 'Go Around'), ('Miss Approach', 'Miss Approach'), ('Bird Strike', 'Bird Strike'), ('Technical Issue', 'Technical Issue')], max_length=50)),
                ('detail_report', models.TextField(blank=True, null=True)),
                ('controller_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
