# Generated by Django 5.2.1 on 2025-05-22 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irsappone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='incident',
            name='operator',
            field=models.CharField(blank=True, help_text='Enter operator name (e.g., Bhutan Airlines)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='place',
            field=models.CharField(blank=True, help_text='Enter location/place of incident', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='call_sign',
            field=models.CharField(help_text='Enter call sign (e.g., DRK, BTN)', max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='occurrence',
            field=models.CharField(help_text='Describe the occurrence (e.g., Go Around, Bird Strike)', max_length=100),
        ),
    ]
